kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "notebooks.fullname" . }}
  labels:
    {{- include "notebooks.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "notebooks.serviceAccountName" . }}
roleRef:
 kind: ClusterRole
 name: {{ include "notebooks.fullname" . }}
 apiGroup: rbac.authorization.k8s.io
